# Generated by Django 4.2.1 on 2023-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='featured_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
