# Generated by Django 4.2.1 on 2023-06-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='featured_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
