# Generated by Django 4.2.1 on 2023-06-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
