# Generated by Django 4.2.1 on 2023-06-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_is_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
